version: "3.9"
############################################
networks:
  kafka:
    name: kafka
############################################
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    networks: 
      - kafka
    env_file: ./zookeeper/.env

  broker-1:
    image: confluentinc/cp-kafka:7.3.0
    hostname: broker-1
    container_name: broker-1
    ports:
      - '9091:9091'
    networks: 
      - kafka
    depends_on: 
      - zookeeper  
    env_file: ./brokers/.broker-1_env
    entrypoint: ["/bin/sh","-c"]
    command: | 
      "
      kafka-topics --bootstrap-server broker-1:29091 --list 
      kafka-topics --bootstrap-server broker-1:29091,localhost:9091 --topic topicA --partitions 3 --replication-factor 1 --if-not-exists --create
      " 

  producer-a:
    build:
      context: ./clients
      args:
        CLIENT_TYPE: producers
    hostname: producer-A
    container_name: producer-A
    environment:
      - CLIENT_ID=producer-A
      - TOPIC=topicA
    networks: 
      - kafka
    depends_on: 
      - zookeeper
      - broker-1  
    env_file: ./clients/producers/.common_producers_env

  consumer-a:
    build:
      context: ./clients
      args:
        CLIENT_TYPE: consumers
    hostname: consumer-A
    container_name: consumer-A
    environment:
      - GROUP_ID=group_1
      - TOPIC=topicA
    networks: 
      - kafka
    depends_on: 
      - zookeeper
      - broker-1  
      - producer-a
    env_file: ./clients/consumers/.common_consumers_env     